# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev1846+g92578e3.d20230915'
__version_tuple__ = version_tuple = (0, 1, 'dev1846', 'g92578e3.d20230915')
